### ISSUE TITLE
Chart test passing but OS Version annotation set to N/A

### ISSUE THREAD

**Issue by mmulholla** [redhat-certification/chart-verifier#111]
In this PR the chart testing passed but the OCVersion annotation was not set. Need to understand why:

https://github.com/openshift-helm-charts/charts/pull/159

**Comment by baijum** [comment]
This is the command used to get the `openshiftVersion` value: [oc version -o yaml](https://github.com/redhat-certification/chart-verifier/blob/c504dafa6737eab2b39049bd65cafb01654e626f/pkg/tool/oc.go#L23)

The above command gives the  `openshiftVersion` value if the logged-in user (role) has access to `get` values of `clusteroperators` (a cluster scoped resource in the `config.openshift.io` API group).

Here is an example ClusterRole:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chart-verifier-cluster-operator-role
rules:
  - apiGroups:
      - "config.openshift.io"
    resources:
      - 'clusteroperators'
    verbs:
      - 'get'
```

Here is the corresponding ClusterRoleBinding:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chart-verifier-cluster-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chart-verifier-cluster-operator-role
subjects:
  - kind: ServiceAccount
    name: <SERVICE-ACCOUNT-NAME>
    namespace: <SERVICE-ACCOUNT-NAMESPACE>
```
(Replace the name of the ServiceAccount and its namespace values)

Can we ask every partner to make these kinds of configuration changes in their cluster? I am not sure a cluster-admin will give these access to developers who run chart-verifier.

These are the two alternatives:
1. Let the user modify the `report.yaml` and update the `certifiedOpenShiftVersions` value after the report generated.
2. Let's introduce a command-line flag, say `openshiftVersion`, and use that value in the report.
    This will be a fallback method if the user doesn't have the above-mentioned access to the `clusteroperators` resource.

My preference would be the second choice. Let me know if there is any concern.
