### ISSUE TITLE
chart-testing fails when using Kubeconfig from Gitlab Kubernetes Agent

### ISSUE THREAD

**Issue by ndegory** [redhat-certification/chart-verifier#253]
I'm using chart-verifier in a Gitlab CI job and would like to leverage the Gitlab Kubernetes Agent connection instead of storing credentials in the project CI/CD variables.
While other jobs with Kubernetes clients (kubectl, helm, oc) with same kubeconfig and kube-context succeed in reaching the OpenShift cluster through the Gitlab Kubernetes Agent, chart-verifier fails with this error:

```
End chart install and test check with NewKubectl error
...
{"check":"v1.0/chart-testing","type":"Mandatory","outcome":"FAIL","reason":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}
...
```

Job specifications:

```
chart-verifier:
  image:
    name: quay.io/redhat-certification/chart-verifier:1.6.0
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  variables:
    CHART_PATH: .
    COMMAND: 'verify'
    DISABLED_TESTS: 'images-are-certified'
    VALUES_FILE: 'ci/openshift-labs.yaml'
    AGENT_PROJECT_PATH: GROUP/PROJECT
    AGENT: openshift-labs
    NAMESPACE: 'ci'
    RELEASE: 'gitlab'
  script:
    - sed -i
          -e "s/BUILD_ID/$CI_PIPELINE_IID/"
          -e "s/NAMESPACE/$NAMESPACE/"
          -e "s/RELEASE/$RELEASE/"
          ci/chart-verifier.yaml
    - /app/chart-verifier
          $COMMAND
          --kubeconfig "$KUBECONFIG"
          --kube-context "$AGENT_PROJECT_PATH:$AGENT"
          --namespace "$NAMESPACE"
          --disable "$DISABLED_TESTS"
          --chart-values "$VALUES_FILE"
          --set-values "ci/chart-verifier.yaml"
          --debug
          "$CHART_PATH" -o json 2>&1 | tee chart-verifier.json
    - 'if grep -q FAIL chart-verifier.json; then exit 1; fi'
  artifacts:
    paths:
      - chart-verifier.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
```

The `ci/chart-verifier.yaml` file used in this job contains:

```
---
chart-testing:
  buildId: BUILD_ID
  upgrade: true
  skipMissingValues: true
  namespace: NAMESPACE
  releaseLabel: "app.kubernetes.io/instance"
  release: RELEASE
```

The agent is configured so that this job is authorized with the cluster-admin permissions on the namespace passed as a flag.

I'm able to successfully connect to that cluster with other client, example here with `oc`, this validates the Gitlab Kubernetes Agent connection:

```
oc-connection:
  image:
    name: quay.io/openshift/origin-cli:4.9.0
  stage: test
  variables:
    CHART_PATH: .
    AGENT_PROJECT_PATH: GROUP/PROJECT
    AGENT: openshift-labs
    NAMESPACE: 'ci'
    RELEASE: 'gitlab'
  script:
    - 'oc config use-context "$AGENT_PROJECT_PATH:$AGENT"'
    - 'oc get all -n "$NAMESPACE"'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      # job is optional, has to triggered manually
      when: manual
      allow_failure: true
```

And I'm also able to reach the cluster with chart-verifier if I bypass the Gitlab Kubernetes Agent by uploading a kubeconfig with a service account token, which validates the chart-verifier job specifications.
