### ISSUE TITLE
I can't override my Chart values

### ISSUE THREAD

**Issue by davividal** [redhat-certification/chart-verifier#465]
I'm trying to verify my chart (https://github.com/SonarSource/helm-chart-sonarqube), but I can't override the default values.

I'm trying to apply [this](https://github.com/SonarSource/helm-chart-sonarqube/pull/526/files#diff-0b1f46ebc6c31e7761ac1eeb0a4fa55d6fe935bfdffa28b6ec8f3a7c4f1fe244) values.yaml:

```yaml
jwtSecret: "dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo="

image:
  image:
  pullSecrets:
    - name: pullsecret
  repository: "sonarsource/sonarqube"
  tag: "10.7.0-community"
```

I tried both commands without success:

```
$ docker run --net host -e KUBECONFIG=/.kube/config -v "${HOME}/.kube/":/.kube/ -v "$(pwd)/charts":/charts:z "quay.io/redhat-certification/chart-verifier" -F /charts/sonarqube/ci/openshift-verifier-values.yaml -n sonarqube verify /charts/sonarqube

$ docker run --net host -e KUBECONFIG=/.kube/config -v "${HOME}/.kube/":/.kube/ -v "$(pwd)/charts":/charts:z "quay.io/redhat-certification/chart-verifier" -S image.tag=10.7.0-community (...) -n sonarqube verify /charts/sonarqube
```

In both cases, it will use the [default](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L33) value for the tag: `10.6.0-community`. This also applies to any other value. Adding `--debug` doesn't show any information.

What am I missing here?
